### PR TITLE
Overdue fixes

### PR DESCRIPTION
**Pull request by lawndoc**
Fixes:
- Removed support for volumes (they create no tangible speed gain)
- Added more reliable Tor Browser version checking for both x64 and arm64 and merged into a single workflow
- Updated Tor Browser to latest version in Dockerfile
- Updated base image from Ubuntu 20.04 to 22.04

### CODE REVIEW

**Comment by lawndoc** [comment]
Closes #53

**Comment by lawndoc** [comment]
Not sure if any others are maintaining this repo anymore. I'll request a review, and if it's not approved in the next couple of days I'll use my permissions to merge these fixes without approval.

**Comment by DomiStyle** [comment]
Looks good to me!

**Comment by lawndoc** [comment]
Thanks for the review @DomiStyle, hope you've been well!

**Pull request merged**
